### ISSUE TITLE
texstudio and texmaker fail with libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format

### ISSUE THREAD

**Issue by plusoptix** [linuxmint/mintcommon#39]
On a Linux Mint Mate Tricia I get the following issue: 
* I installed a texstudio 
dpkg -l "texstudio"
ii  texstudio                                                                 2.12.22-0~202001151910~ubuntu18.04.1      
* texmaker
ii  texmaker                                                                  5.0.2-1build2  
on both I get a 
texmaker: symbol lookup error: /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format
texstudio: symbol lookup error: /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format

google tells me, that it is a freetype problem. So I checked freetype:
dpkg -l "*freetype*"
un  gir1.2-freetype2-2.0                                                      <keine>                                   <keine> 
un  libfont-freetype-perl                                                     <keine>                                   <keine> 
ii  libfreetype6:amd64                                                        2.8.1-2ubuntu2                            amd64  
ii  libfreetype6-dev:amd64                                                    2.8.1-2ubuntu2 

libQt5XcbQpa.so.5 is part of the package libqt5gui5:
dpkg -l "libqt5gui5"
ii  libqt5gui5:amd64                                                          5.9.5+dfsg-0ubuntu2.5 

Now the funny part: I have an identical machine here (lshw Produkt: 81HN (LENOVO_MT_81HN_BU_idea_FM_V130-15IKB)), same system but different update status: 
the one with the error did the last update: 
Start-Date: 2020-03-10  11:28:54
Commandline: aptdaemon role='role-install-packages' sender=':1.328'
Install: libpoppler-qt5-1:amd64 (0.62.0-2ubuntu2.10, automatic), libqt5xml5:amd64 (5.9.5+dfsg-0ubuntu2.5, automatic), texstudio:amd64 (2.12.22-0~202001151910~ubuntu18.04.1), libqt5printsupport5:amd64 (5.9.5+dfsg-0ubuntu2.5, automatic), libqt5concurrent5:amd64 (5.9.5+dfsg-0ubuntu2.5, automatic), libqt5script5:amd64 (5.
9.5+dfsg-0ubuntu1, automatic)
End-Date: 2020-03-10  11:28:59

and the one, on which the same texmaker and texstudio version work updates last time: 
Start-Date: 2020-03-05  17:25:42
Commandline: /usr/sbin/synaptic --hide-main-window --non-interactive --parent-window-id 90177556 -o Synaptic::closeZvt=true --set-selections-file /tmp/tmp47ajxcq5
Requested-By: prakti2 (1000)
Install: ...
End-Date: 2020-03-05  17:32:16

The texmake, texstudio, libqt5gui5, freetype packages are identical.
It seems, in between there must be a change in some changes in a different package. Attached you can find the packagelist of the both pcs: packagelist1 is where it does not work, packagelist2 is, where it works.

**Comment by plusoptix** [comment]
[packagelist1.txt](https://github.com/linuxmint/mintcommon/files/4329648/packagelist1.txt)
[packagelist2.txt](https://github.com/linuxmint/mintcommon/files/4329663/packagelist2.txt)

At the not so updated but working pc I would get the following update suggest (I don't do it, so I could use the texstudio furtheron on it)
$ apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-34 linux-headers-4.15.0-34-generic linux-headers-4.15.0-36 linux-headers-4.15.0-36-generic linux-headers-4.15.0-38 linux-headers-4.15.0-38-generic linux-headers-4.15.0-39 linux-headers-4.15.0-39-generic linux-headers-4.15.0-42 linux-headers-4.15.0-42-generic linux-headers-4.15.0-45
  linux-headers-4.15.0-45-generic linux-headers-4.15.0-54 linux-headers-4.15.0-54-generic linux-headers-4.15.0-55 linux-headers-4.15.0-55-generic linux-headers-4.15.0-58 linux-headers-4.15.0-58-generic linux-headers-4.15.0-60 linux-headers-4.15.0-60-generic linux-headers-4.15.0-62 linux-headers-4.15.0-62-generic
  linux-image-4.15.0-34-generic linux-image-4.15.0-36-generic linux-image-4.15.0-38-generic linux-image-4.15.0-39-generic linux-image-4.15.0-42-generic linux-image-4.15.0-45-generic linux-image-4.15.0-54-generic linux-image-4.15.0-55-generic linux-image-4.15.0-58-generic linux-image-4.15.0-60-generic
  linux-image-4.15.0-62-generic linux-modules-4.15.0-34-generic linux-modules-4.15.0-36-generic linux-modules-4.15.0-38-generic linux-modules-4.15.0-39-generic linux-modules-4.15.0-42-generic linux-modules-4.15.0-45-generic linux-modules-4.15.0-54-generic linux-modules-4.15.0-55-generic
  linux-modules-4.15.0-58-generic linux-modules-4.15.0-60-generic linux-modules-4.15.0-62-generic linux-modules-extra-4.15.0-62-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  adobe-flashplugin code cpp-7 cpp-7-arm-linux-gnueabi cpp-7-arm-linux-gnueabihf firefox firefox-locale-en g++-7 g++-7-arm-linux-gnueabi gcc-7 gcc-7-arm-linux-gnueabi gcc-7-arm-linux-gnueabi-base gcc-7-arm-linux-gnueabihf gcc-7-arm-linux-gnueabihf-base gcc-7-base gcc-7-cross-base gcc-8-base gcc-8-base:i386
  gir1.2-networkmanager-1.0 libasan4 libasan4-armel-cross libasan4-armhf-cross libatomic1:i386 libatomic1 libcc1-0 libcilkrts5 libcilkrts5-armel-cross libcilkrts5-armhf-cross libgcc-7-dev libgcc-7-dev-armel-cross libgcc-7-dev-armhf-cross libgcc1 libgcc1:i386 libgfortran4 libgomp1 libitm1 liblsan0 libmpx2 libnm-glib4
  libnm-util2 libnm0 libquadmath0 libsqlite3-0:i386 libsqlite3-0 libstdc++-7-dev libstdc++-7-dev-armel-cross libstdc++6 libstdc++6:i386 libtsan0 libubsan0 libubsan0-armel-cross libubsan0-armhf-cross linux-firmware network-manager network-manager-config-connectivity-ubuntu
55 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 274 MB of archives.

Another difference - the kernel: 
Linux hwprakti2 4.18.7-041807-generic #201809090930 SMP Sun Sep 9 09:33:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
(on the pc, where texstudio is still working)
and 
Linux hwprakti1 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(on the pc with the error)

**Comment by xenopeek** [comment]
Hi, for help with troubleshooting to find the cause of this I suggest to make a topic on the [support forum](https://forums.linuxmint.com/viewforum.php?f=47). If it turns out the problem is with a component developed or maintained by Linux Mint this issue can be reopened here but it first needs further troubleshooting to determine the responsible component. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).

The one thing I can add is that you installed texstudio from outside the official repositories as [that has version 2.12.6 currently](https://packages.ubuntu.com/bionic/texstudio) while you show 2.12.22 installed. Maybe you added a repository or you installed it from a .deb file downloaded from from the texstudio website. I'd look into this next. You could try downgrading it with command `apt install texstudio/bionic` and see if that makes a difference.
