### ISSUE TITLE
Wireguard and Network Manager

### ISSUE THREAD

**Issue by xaozai** [linuxmint/mintcommon#46]
NetworkManager 1.16 [got](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/NEWS?id=1.16.0) native support for WireGuard VPN tunnels.
There is no menu item for adding a Wireguard tunnel in xfce.
How do i fix it?

OS: Linuxmint 20.2 uma
Kernel: x86_64 Linux 5.4.0-91-generic
nmcli: 1.22.10
xfce4-session: 4.16.0

network-manager-gnome/uma,now 1.8.24-linuxmint4 amd64 [installed]
network-manager-openconnect-gnome/focal,now 1.2.6-1 amd64 [installed]
network-manager-pptp-gnome/focal,now 1.2.8-2 amd64 [installed]

**Comment by xaozai** [comment]
NetworkManager version 1.26.2 and higher, allows to create a WireGuard-type connection with GUI.
Please update it.

**Comment by xenopeek** [comment]
Linux Mint 20.x releases are based on Ubuntu 20.04 LTS and that has Network Manager 1.22. If you need a newer Network Manager version on Linux Mint 20.x I would suggest asking for help with that on the support forums. There is a plugin that is reported to work (requires compiling it): https://github.com/max-moser/network-manager-wireguard. Linux Mint 21, expected around mid next year, will be based on Ubuntu 22.04 LTS and that will have at least Network Manager 1.32.
