### ISSUE TITLE
Can't remove Pix and Rhythmbox because of their own packages. Reverse dependents logic isn't good - we should use important packages logic instead, like in mintupgrade

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/mintcommon#58]
Just see for youself:
![pix](https://github.com/linuxmint/mintcommon/assets/118076740/f7e1c18b-0262-43db-a588-1914dc9071dd)
![rhythmbox](https://github.com/linuxmint/mintcommon/assets/118076740/3b116b18-b7c6-4628-9b83-aa5af2cc42c8)
i. e. a package can't be removed because that would lead to the removal of "helper packages". That's too stupid ;)

**Comment by fredcw** [comment]
The menu applet uses a fairly simple uninstall script that won't remove dependant packages to avoid accidental removal of system packages - e.g. removing Nemo would also remove Cinnamon. You can however remove Pix using mint software manager.

But I would agree that circular dependencies like this seem illogical. Maybe there's a good reason for it, I don't know.

**Comment by clefebvre** [comment]
@fredcw the dep check was made by you? https://github.com/linuxmint/mintcommon/commit/196da68a0e2b54f9d31db7d28c9e9ff0f8290006

Maybe we can relax it a bit.

**Comment by clefebvre** [comment]
I think the main issue is removing parts of the DE... say you remove "Colors" from the menu, which is the `cinnamon-control-center` pkg... 

It wants to remove cinnamon-control-center, cinnamon, mint-meta-cinnamon etc... so it's not good.

If you pick `Accessibility` it'll want to remove cinnamon, mint-meta-cinnamon... not good either.

Right now the code checks for the number of dependencies, in case it should probably have a list of names and prefixes that it won't let you remove?

say XDG_CURRENT_DESKTOP says Cinnamon, it's probably not a good idea to remove cinnamon... just one example.

If you want to get rid of pix though, and all that stops it is pix-dbg, it shouldn't be a problem.

**Comment by fredcw** [comment]
@clefebvre Agreed. I'll fix it.
